sudo: required
services:
  - docker

script:
  - docker build -t ericvdal/test .
  - docker images ericvdal/test

before_deploy:
  - docker login -u ericvdal -p DP2l1can2t!R

  deploy:
    provider: script
    script: docker push ericvdal/test
    on:
      branch: master